version: 2

setup_ftl: &setup_ftl
  - run:
      name: Authorize gcloud and set config defaults
      command: |
        echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/gcloud-service-key.json
        sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

jobs:
  build_and_setup:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            ./gradlew assembleDebug
            ./gradlew assembleInstalledStagingAndroidTest
      - persist_to_workspace:
          root: .
          paths:
            - ./*/mobile/build
  run_unit_tests:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: |
            ./gradlew test

  run_ftl:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - <<: *setup_ftl
      - run:
          name: Test BasicSample with Firebase Test Lab
          command: |
            BUILD_DIR=build_${CIRCLE_BUILD_NUM}
            sudo gcloud firebase test android run \
              --app mobile/build/outputs/apk/installed/staging/mobile-installed-staging.apk \
              --test mobile/build/outputs/apk/androidTest/installed/staging/mobile-installed-staging-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}-iosched \
              --results-dir=${BUILD_DIR}
      - run:
         name: Download results
         command: |
            BUILD_DIR=build_${CIRCLE_BUILD_NUM}
            sudo pip install -U crcmod
            mkdir firebase_test_results
            sudo gsutil -m mv -r -U `sudo gsutil ls gs://cloud-test-${GOOGLE_PROJECT_ID}-iosched/${BUILD_DIR} | tail -1` firebase_test_results/ | true
      - store_artifacts:
          path: firebase_test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup
      - run_unit_tests:
          requires:
            - build_and_setup
      - run_ftl:
          requires:
            - build_and_setup
